Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@same'

Options:
 test-before-installing: True
 enable-lsan: True
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
